apiVersion: v2
name: ato-teamcity
description: A Helm chart to deploy a Jetbrains TeamCity CICD Server on Kubernetes
version: 0.1.6
appVersion: "2022.10.3"
icon: "https://avatars.githubusercontent.com/u/94903315?s=200&v=4"
maintainers:
- email: support@allthingsops.io
  name: allThingsOps