apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-teamcity-server
  labels:
    app: teamcity-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8111
          protocol: TCP 